### ISSUE TITLE
Make realtime-rest.js a real module

### ISSUE THREAD

**Issue by mingfang** [SocketCluster/sc-sample-inventory#1]
realtime-rest.js looks very nice and can be useful for many real project if it was a real module.

**Comment by jondubois** [comment]
@mingfang Good timing, I've just released sc-crud-rethink (available from npm). https://github.com/SocketCluster/sc-crud-rethink :p

**Comment by jondubois** [comment]
Also, I made a lot of changes to this sc-sample-inventory repo (it's now using the proper sc-crud-rethink plugin/module instead of the old realtime-rest.js plugin) so you can see how sc-crud-rethink works and how it interacts with Polymer components like sc-collection and sc-field.
